# Generated by Django 4.0.4 on 2022-04-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_train',
            name='img',
        ),
    ]
