# Generated by Django 4.0.4 on 2022-05-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100, null=True)),
                ('date2', models.DateField(null=True)),
                ('fare', models.IntegerField(null=True)),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='train.passenger')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='train.register')),
            ],
        ),
    ]
