# Generated by Django 4.0.4 on 2022-05-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_book_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
    ]
